### ISSUE TITLE
BUG: undefined references to everything

### ISSUE THREAD

**Issue by florisvb** [basler/pylon-ros-camera#251]
### Issue description

I am trying to get this package (branch: master) to work on a system running Ubuntu 20.04 with ROS Noetic. What I get to the catkin make step I get a long sequence of undefined references. 

### Code example about how to reproduce the issue

cd ~/catkin_ws && catkin_make clean && catkin_make && source ~/.bashrc

### Error message

```shell
[ 96%] Linking CXX executable /home/buzz/catkin_ws/devel/lib/pylon_camera/set_device_user_id
[ 96%] Generating Python msg __init__.py for camera_control_msgs
[ 96%] Built target camera_control_msgs_generate_messages_cpp
[ 96%] Generating Python srv __init__.py for camera_control_msgs
/usr/bin/ld: CMakeFiles/set_device_user_id.dir/src/pylon_camera/set_device_user_id.cpp.o: in function `main':
set_device_user_id.cpp:(.text+0x507): undefined reference to `Pylon::PylonInitialize()'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x528): undefined reference to `Pylon::CDeviceInfo::CDeviceInfo()'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x52d): undefined reference to `Pylon::CTlFactory::GetInstance()'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x560): undefined reference to `Pylon::CInstantCamera::CInstantCamera(Pylon::IPylonDevice*, Pylon::ECleanup)'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x56f): undefined reference to `Pylon::CInstantCamera::Open()'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x57e): undefined reference to `Pylon::CInstantCamera::GetNodeMap()'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x5a9): undefined reference to `GenICam_3_1_Basler_pylon::gcstring::gcstring(char const*)'
/usr/bin/ld: set_device_user_id.cpp:(.text+0x5f3): undefined reference to 

.......


`GenICam_3_1_Basler_pylon::gcstring::~gcstring()'
/usr/bin/ld: CMakeFiles/IPConfigAuto.dir/src/pylon_camera/IPConfigAuto.cpp.o:(.data.rel.local.DW.ref._ZTIN24GenICam_3_1_Basler_pylon16GenericExceptionE[DW.ref._ZTIN24GenICam_3_1_Basler_pylon16GenericExceptionE]+0x0): undefined reference to `typeinfo for GenICam_3_1_Basler_pylon::GenericException'
collect2: error: ld returned 1 exit status
make[2]: *** [pylon-ros-camera/pylon_camera/CMakeFiles/IPConfigAuto.dir/build.make:84: /home/buzz/catkin_ws/devel/lib/pylon_camera/IPConfigAuto] Error 1
make[1]: *** [CMakeFiles/Makefile2:5087: pylon-ros-camera/pylon_camera/CMakeFiles/IPConfigAuto.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j72 -l72" failed
```

### Hardware setup description

Ubuntu 20.04 x86_64

### Runtime information

```shell
I have pylon 6.2 installed, I have also tried with 6.3 and 7.3. All of the pylon viewer versions work. 
I am running ROS Noetic.
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by FrancoisPicardDTI** [comment]
Hello @florisvb 
The master branch support the ROS version of the pylon driver, this is a deprecated version, we are not maintaining anymore.
I suggest that you upgrade to the ROS2 galactic version if you want to stay under Ubuntu 20.04, and thus upgrading your pylon version as well.
